---
local_users:
  - name: devops
    comment: "DevOps test user"
    groups: wheel
    shell: /bin/bash

common_packages:
  - vim
  - git
  - curl
  - wget
  - net-tools
  - bind-utils

loki_server_ip: "192.168.56.20"
loki_http_port: 3100
