---
- name: Base setup for all nodes
  hosts: all_nodes
  become: yes

  roles:
    - common

- name: User management on target node
  hosts: target
  become: yes

  roles:
    - users

- name: Install Loki on monitoring node
  hosts: monitoring
  become: yes

  roles:
    - loki

- name: Install Alloy log agent on management and target nodes
  hosts: management:target
  become: yes

  roles:
    - alloy
