---
- name: Create local users
  hosts: all
  become: yes

  vars:
    local_users:
      - name: devops
        comment: "DevOps test user"
        groups: wheel
        shell: /bin/bash
        password_hash: "{{ devops_password_hash }}"

  tasks:
    - name: Create users
      ansible.builtin.user:
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        groups: "{{ item.groups }}"
        append: yes
        shell: "{{ item.shell }}"
        password: "{{ item.password_hash }}"
        state: present
      loop: "{{ local_users }}"
      no_log: true
