---
- name: Manage users
  hosts: all
  become: yes

  vars:
    local_users:
      - name: devops
        comment: "DevOps test user"
        groups: wheel
        shell: /bin/bash

  roles:
    - users
